[package]
name = "genemichaels"
version = "0.1.0"
edition = "2021"
license = "ISD"
description = "Makes your code formatty"
repository = "https://github.com/andrewbaxter/genemichaels"
readme = "readme.md"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
icu_segmenter = { version = "0.7.0", features = ["lstm"] }
icu_testdata = "1.0.0"
proc-macro2 = { version = "1.0.47", features = ["span-locations"] }
pulldown-cmark = "0.9.2"
quote = "1.0.21"
structre = "0.0.1"
syn = { version = "1.0.105", features = ["full"] }
